abds([fight/1]).

save_princess <- minion(X), fight(X), prolog(survive_from(X)).
save_princess <- minion(X), fight(X).




beginProlog.
survive_from(X) :- pr_survival(X,P), P > 0.6.

pr_survival(spider,0.4).
pr_survival(ninja,0.7).
endProlog.

%utilitarian <- not knight.

minion(spider).
minion(ninja).

human(ninja).

%%%

false <- know_gandhi, not follow_gandhi.
follow_gandhi <- minion(X), human(X), not fight(X).